### ISSUE TITLE
[Feature Request] Add Battery Stats Feature

### ISSUE THREAD

**Issue by TuxKruger** [SmartPack/SmartPack-Kernel-Manager#78]
Hello Dev,

I am loving your amazing Kernel Manager so far. I was comparing it to Franco Kernel Manager the other day (I know I shouldn't but I was curious to see the difference between the two). I got to know that almost everything is more easier on Smartpack for me. But it lacks one really nice feature that Franco Kernel Manager got - Battery Stats. This feature lets one know about the Active Drain, Idle drain etc (you can refer to screenshots). 

![Screenshot_20200915-084837_Franco_Kernel_Manager](https://user-images.githubusercontent.com/39946309/93161484-48cb5f00-f730-11ea-9c0b-895b057a05b4.png)
![Screenshot_20200915-084828_Franco_Kernel_Manager](https://user-images.githubusercontent.com/39946309/93161486-4a952280-f730-11ea-9d96-c6029e6834a3.png)
![Screenshot_20200915-084820_Franco_Kernel_Manager](https://user-images.githubusercontent.com/39946309/93161489-4b2db900-f730-11ea-8bbb-20a8484c16ca.png)
![Screenshot_20200915-092006_Franco_Kernel_Manager~2](https://user-images.githubusercontent.com/39946309/93163435-c3967900-f734-11ea-8e21-4ec34ae6f3c2.png)

I request you to add a similar feature to monitor Active Drain, Idle Drain etc.

**Comment by sunilpaulmathew** [comment]
@TuxKruger 
Thank you very much for the nice words about the app and also for raising this issue. I know many people like to have a battery monitor on my app. However, I am currently against that feature because of a number of reasons.
1. It requires the app to be running in background for 24*7 (drain more battery).
2. I personally don't think it gives much benefits to users than a fancy view to fool them.
3. I really like to add more kernel-level features, that offer more control over the kernel.
I hope you will understand my philosophy on this app.

**PS**: If you really wish to have such a feature, I suggest [Battery Guru](https://play.google.com/store/apps/details?id=com.paget96.batteryguru&hl=en), an app dedicated to give such features.

**Comment by TuxKruger** [comment]
Thank you very much for replying and explaining why you are not adding battery monitor. Adding to this I wanna say, battery monitor won't suck much battery. I use it almost daily on FKM and I never faced much drain and it was almost the same if I am not using it. Anyways, ig in the end it is dev's own choice to add a feature or not. Keep up the good work and I will try BatteryGuru once (it is not open-source (or is it?), so I never considered to try it but looks like now it is time to try).

**Comment by sunilpaulmathew** [comment]
> Thank you very much for replying and explaining why you are not adding battery monitor. Adding to this I wanna say, battery monitor won't suck much battery. I use it almost daily on FKM and I never faced much drain and it was almost the same if I am not using it. Anyways, ig in the end it is dev's own choice to add a feature or not. Keep up the good work and I will try BatteryGuru once (it is not open-source (or is it?), so I never considered to try it but looks like now it is time to try).

Thanks for understanding.
Also, SPKM is much more heavier app. So, running it in background may not be a good idea. Also, although battery guru is not opensource, it is coming from a trusted developer who is very active in development for years.
